create trigger AUTOR_NASCUT_INAINTE_PUBLICARE
    before insert or update of COD_AUTOR,DATA_PUBLICARE
    on EBOOKURI
    for each row
DECLARE
    DATA_NASTERE DATE;
BEGIN
    SELECT DATA_NASTERII INTO DATA_NASTERE
    FROM AUTORI A
    WHERE A.COD_AUTOR = :NEW.COD_AUTOR;

    IF :NEW.DATA_PUBLICARE < DATA_NASTERE THEN
        RAISE_APPLICATION_ERROR(
        -20071, 'DATA PUBLICARII NU POATE FI INAINTE DE DATA NASTERII AUTORULUI'
        );
    end if;
end;
/

