create trigger DATA_RECENZIE_CORECTA
    before insert or update of DATA_PUBLICARE
    on RECENZII
    for each row
DECLARE
    DATA_PUBLICARE_EBOOK DATE;
    DATA_PRIMA_COMANDA_PLASATA_EBUT DATE;
BEGIN

    IF :NEW.DATA_PUBLICARE IS NULL THEN
        RETURN;
    end if;

    IF :NEW.DATA_PUBLICARE > SYSDATE THEN
        RAISE_APPLICATION_ERROR(
        -20030, 'DATA RECENZIEI NU POATE FI IN VIITOR'
        );
    end if;

    SELECT
        DATA_PUBLICARE INTO DATA_PUBLICARE_EBOOK
    FROM EBOOKURI
    WHERE COD_EBOOK = :NEW.COD_EBOOK;

    SELECT
        MIN(C.DATA_PLASARE) INTO DATA_PRIMA_COMANDA_PLASATA_EBUT
    FROM COMENZI C
    JOIN DETALII_PRODUS DP ON DP.COD_COMANDA = C.COD_COMANDA
    WHERE C.COD_UT = :NEW.COD_UT AND DP.COD_EBOOK = :NEW.COD_EBOOK;

    IF :NEW.DATA_PUBLICARE < DATA_PUBLICARE_EBOOK THEN
        RAISE_APPLICATION_ERROR(
        -20031, 'DATA RECENZIEI NU POATE FI INAINTE DE DATA DE PUBLICARE A EBOOKULUI'
        );
    end if;

    IF :NEW.DATA_PUBLICARE < DATA_PRIMA_COMANDA_PLASATA_EBUT THEN
        RAISE_APPLICATION_ERROR(
        -20032, 'DATA RECENZIEI NU POATE FI INAINTE DE DATA COMENZII'
        );
    end if;

end;
/

