create trigger EDITURA_INFIINTATA_INAINTE_PUBLICARE
    before insert or update of COD_EDITURA,DATA_PUBLICARE
    on EBOOKURI
    for each row
DECLARE
    DATA_INF DATE;
BEGIN
    SELECT
        DATA_INFIINTARE INTO DATA_INF
    FROM EDITURI E
    WHERE E.COD_EDITURA = :NEW.COD_EDITURA;

    IF :NEW.DATA_PUBLICARE < DATA_INF THEN
        RAISE_APPLICATION_ERROR(
        -20072, 'EBOOKUL NU POATE FI PUBLICAT INAINTE DE INFIINTAREA EDITURII'
        );
    end if;

end;
/

