create trigger PUBLICARE_EBOOK_INAINTE_COMANDA
    before insert or update of COD_EBOOK,COD_COMANDA
    on DETALII_PRODUS
    for each row
DECLARE
    DATA_COMANDA DATE;
    DATA_PUBLICARE_EBOOK DATE;
BEGIN
    SELECT
        DATA_PLASARE INTO DATA_COMANDA
    FROM COMENZI C
    WHERE C.COD_COMANDA = :NEW.COD_COMANDA;

    SELECT
        DATA_PUBLICARE INTO DATA_PUBLICARE_EBOOK
    FROM EBOOKURI E
    WHERE E.COD_EBOOK = :NEW.COD_EBOOK;

    IF DATA_PUBLICARE_EBOOK >  DATA_COMANDA THEN
        RAISE_APPLICATION_ERROR(
        -20041, 'NU SE POATE COMANDA UN EBOOK NEPUBLICAT LA DATA COMENZII'
        );
    end if;

end;
/

