create trigger RECENZIE_VALIDA
    before insert
    on RECENZII
    for each row
DECLARE
    CONTOR NUMBER;
BEGIN
    SELECT
        COUNT(*) INTO CONTOR
    FROM COMENZI C
    JOIN DETALII_PRODUS DP ON DP.COD_COMANDA = C.COD_COMANDA
    WHERE C.COD_UT = :NEW.COD_UT
          AND DP.COD_EBOOK = :NEW.COD_EBOOK;

    IF CONTOR = 0 THEN
        RAISE_APPLICATION_ERROR(
        -20001, 'RECENZIA NU POATE FI ADAUGATA: UTILIZATORUL NU A CUMPARAT ACEST EBOOK'
        );
    end if;
END;
/

