create trigger UPDATE_DELETE_DETALII_PRODUS
    before update or delete
    on DETALII_PRODUS
BEGIN
    RAISE_APPLICATION_ERROR(
    -20080, 'DETALIILE UNEI COMENZI PLASATE NU POT FI MODIFICATE SAU STERSE'
    );
end;
/

