create PROCEDURE CARTI_AUTORI(CATEGORIE CATEGORII.NUME_CAT%TYPE)
IS
    NUMAR_CARTI NUMBER;

    TYPE TABLOU_INDEXAT IS TABLE OF EBOOKURI.NUME_EBOOK%TYPE INDEX BY PLS_INTEGER;
    CATEGORIE_CARTI TABLOU_INDEXAT;

    TYPE TABLOU_IMBRICAT IS TABLE OF AUTORI.NUME_AUTOR%TYPE;
    CARTE_AUTOR TABLOU_IMBRICAT := TABLOU_IMBRICAT();

    TYPE VECTOR IS VARRAY(3) OF VARCHAR2(100);
    TOP3 VECTOR := VECTOR();

BEGIN

    SELECT
        COUNT(C.COD_CATEGORIE) INTO NUMAR_CARTI
    FROM EBOOKURI E
    JOIN CATEGORII C ON C.COD_CATEGORIE = E.COD_CATEGORIE
    WHERE C.NUME_CAT = CATEGORIE;

    IF NUMAR_CARTI > 0 THEN

        DBMS_OUTPUT.PUT_LINE('CARTILE DIN CATEGORIA ' || CATEGORIE || ' SUNT: ');

        SELECT
            E.NUME_EBOOK BULK COLLECT INTO CATEGORIE_CARTI
        FROM EBOOKURI E
        JOIN CATEGORII C ON C.COD_CATEGORIE = E.COD_CATEGORIE
        WHERE C.NUME_CAT = CATEGORIE;

        SELECT
            A.PRENUME_AUTOR || ' ' || A.NUME_AUTOR BULK COLLECT INTO CARTE_AUTOR
        FROM EBOOKURI E
        JOIN CATEGORII C ON C.COD_CATEGORIE = E.COD_CATEGORIE
        JOIN AUTORI A ON A.COD_AUTOR = E.COD_AUTOR
        WHERE C.NUME_CAT = CATEGORIE;

        FOR I IN CATEGORIE_CARTI.FIRST..CATEGORIE_CARTI.LAST LOOP
            DBMS_OUTPUT.PUT_LINE(CATEGORIE_CARTI(I) || ' scrisa de ' || CARTE_AUTOR(I));
            end loop;
        DBMS_OUTPUT.NEW_LINE;

        DBMS_OUTPUT.PUT_LINE('TOP CELE MAI RECENTE CARTI DIN CATEGORIA ' || CATEGORIE || ' :');

        SELECT
            NUME_EBOOK BULK COLLECT INTO TOP3
        FROM (
            SELECT
                E.NUME_EBOOK
            FROM EBOOKURI E
            JOIN CATEGORII C ON C.COD_CATEGORIE = E.COD_CATEGORIE
            WHERE C.NUME_CAT = CATEGORIE
            ORDER BY E.DATA_PUBLICARE DESC
             )
        WHERE ROWNUM <= 3;

        FOR I IN 1..TOP3.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE(I || '. ' || TOP3(I));
            DBMS_OUTPUT.NEW_LINE();
            end loop;

    ELSE
        DBMS_OUTPUT.PUT_LINE('ACEASTA CATEGORIE NU ARE CARTI');
    end if;

end CARTI_AUTORI;
/

