create PROCEDURE UTILIZATORI_DISCOUNTURI IS

    DISC DISCOUNTURI.COD_DIS%TYPE;

    CURSOR DISCOUNTURIC IS
        SELECT
            COD_DIS,
            NUME_DIS
        FROM DISCOUNTURI D;

    CURSOR UTILIZATORI_DIS(COD_DISCOUNT DISCOUNTURI.COD_DIS%TYPE) IS
        SELECT
            COUNT(U.COD_UT) NUMAR_UTILIZARI_DIS,
            COUNT(DISTINCT U.COD_UT) NUMAR_UTILIZATORI_DIS
        FROM DISCOUNTURI D
        JOIN COMENZI C ON C.COD_DIS = D.COD_DIS
        JOIN UTILIZATORI U ON C.COD_UT = U.COD_UT
        WHERE D.COD_DIS = COD_DISCOUNT;

    BEGIN

        FOR I IN DISCOUNTURIC LOOP
            DISC := I.COD_DIS;
            FOR J IN UTILIZATORI_DIS(DISC) LOOP
                IF J.NUMAR_UTILIZARI_DIS > 0 THEN
                    DBMS_OUTPUT.PUT_LINE('DISCOUNTUL ' || I.NUME_DIS || ' A FOST UTILIZAT DE: ' || J.NUMAR_UTILIZARI_DIS || ' ORI / NUMAR UTILIZATORI: ' || J.NUMAR_UTILIZATORI_DIS);
                ELSE
                    DBMS_OUTPUT.PUT_LINE('DISCOUNTUL ' || I.NUME_DIS || ' NU A FOST UTILIZAT DE NICIUN UTILIZATOR');
                end if;
            end loop;
        end loop;

END UTILIZATORI_DISCOUNTURI;
/

