INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (1, 'LITERATURA CLASICA');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (2, 'SF');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (3, 'FANTASY');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (4, 'THRILLER');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (5, 'ROMANCE');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (6, 'DRAMA');
INSERT INTO ADAPROIECT.CATEGORII (COD_CATEGORIE, NUME_CAT) VALUES (7, 'LITERATURA CONTEMPORANA');
