INSERT INTO ADAPROIECT.DISCOUNTURI (COD_DIS, NUME_DIS, PROCENT, VALABILITATE) VALUES (1, 'REDUCERE DE AUTOR', 30.00, DATE '2026-04-15');
INSERT INTO ADAPROIECT.DISCOUNTURI (COD_DIS, NUME_DIS, PROCENT, VALABILITATE) VALUES (2, 'PAGINI LA JUMATATE', 50.00, DATE '2026-07-16');
INSERT INTO ADAPROIECT.DISCOUNTURI (COD_DIS, NUME_DIS, PROCENT, VALABILITATE) VALUES (3, 'BIBLIOTECA LA ORET MIC', 70.00, DATE '2026-09-28');
INSERT INTO ADAPROIECT.DISCOUNTURI (COD_DIS, NUME_DIS, PROCENT, VALABILITATE) VALUES (8, 'ULTIMUL PRET', 40.00, DATE '2025-04-05');
INSERT INTO ADAPROIECT.DISCOUNTURI (COD_DIS, NUME_DIS, PROCENT, VALABILITATE) VALUES (9, 'EVENIMENT', 90.00, DATE '2026-01-22');
