create PACKAGE PACHET_RECENZII AS

    TYPE RECENZIE_T IS RECORD(COD_EBOOK NUMBER, COD_UT NUMBER, RATING NUMBER);

    TYPE LISTA_RECENZII IS TABLE OF RECENZIE_T
        INDEX BY PLS_INTEGER;

    FUNCTION MEDIE_RATING_EBOOK(COD_EBOOK_MED NUMBER)
        RETURN NUMBER;

    FUNCTION RECENZII_RATING_MAX(COD_EBOOK_MAX NUMBER)
        RETURN NUMBER;

    PROCEDURE ADAUGA_RECENZIE(LISTA LISTA_RECENZII);

    PROCEDURE STERGE_RECENZIE(COD_RECENZIE_DEL NUMBER);

END PACHET_RECENZII;
/

create PACKAGE BODY PACHET_RECENZII AS

    FUNCTION MEDIE_RATING_EBOOK(COD_EBOOK_MED NUMBER) RETURN NUMBER IS

        MEDIE NUMBER;

        BEGIN
            SELECT
                AVG(RATING) INTO MEDIE
            FROM RECENZII
            WHERE COD_EBOOK = COD_EBOOK_MED;

        RETURN MEDIE;
    END;

    FUNCTION RECENZII_RATING_MAX(COD_EBOOK_MAX NUMBER) RETURN NUMBER IS
        NR NUMBER;

        BEGIN
            SELECT
                COUNT(*) INTO NR
            FROM RECENZII
                WHERE COD_EBOOK = COD_EBOOK_MAX AND RATING = 5;
            RETURN NR;
    END;

        PROCEDURE ADAUGA_RECENZIE(LISTA LISTA_RECENZII) IS
            BEGIN
                FOR I IN LISTA.FIRST .. LISTA.LAST LOOP
                INSERT INTO RECENZII (COD_RECENZIE, COD_EBOOK, COD_UT, DATA_PUBLICARE, RATING)
                VALUES (SEQ_RECENZII.NEXTVAL,  LISTA(I).COD_EBOOK, LISTA(I).COD_UT, SYSDATE, LISTA(I).RATING);
                    end loop;

        END;

        PROCEDURE STERGE_RECENZIE(COD_RECENZIE_DEL NUMBER) IS
            BEGIN
                DELETE FROM RECENZII
                WHERE COD_RECENZIE = COD_RECENZIE_DEL;
        END;


END PACHET_RECENZII;
/

